apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myskaffoldplanet
  name: myskaffoldplanet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myskaffoldplanet
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myskaffoldplanet
    spec:
      containers:
        - image: docker.io/mydeveloperplanet/myskaffoldplanet
          name: myskaffoldplanet
          resources: {}
status: {}