apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: myskaffoldplanet
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: myskaffoldplanet
  type: NodePort
status:
  loadBalancer: {}